image: gcc

before_script:
  - apt-get update
  - apt-get install libgtk-3-dev -y
  - apt-get install libwebkit2gtk-4.0-dev -y
  - apt-get install meson -y

cache:
  paths:
    - build

build:
  stage: build
  script:
    - meson setup build .
    - meson compile -C build

test:
  stage: test
  script:
    - meson test -C build
